edit_uri: ''
google_analytics:
- UA-27795084-5
- mkdocs.org
markdown_extensions:
- toc:
    permalink: '#'
nav:
- Home: index.md
- Post:
  - Introduction: Post/index.md
  - Thoughts: Post/Thoughts.md
  - Abstraction:
    - Abstraction: Post/Abstraction/Abstraction.md
    - Abstraction-and-architecture: Post/Abstraction/Abstraction-and-architecture.md
    - Abstraction-and-architecture-and-layer: Post/Abstraction/Abstraction-and-architecture-and-layer.md
    - Abstraction-and-model: Post/Abstraction/Abstraction-and-model.md
    - Abstraction-and-relation: Post/Abstraction/Abstraction-and-relation.md
    - Abstraction-and-virtual: Post/Abstraction/Abstraction-and-virtual.md
  - Language:
    - Language: Post/Language/Language.md
  - Formal:
    - Formal: Post/Formal/Formal.md
  - Recursion:
    - Introduction: Post/Recursion/index.md
    - Recursive-Definition: Post/Recursion/Recursive-Definition.md
    - Recursion: Post/Recursion/Recursion.md
    - Corecursion: Post/Recursion/Corecursion.md
    - Induction-and-deduction:
      - Introduction: Post/Recursion/Induction-and-deduction/index.md
      - Induction-and-deduction: Post/Recursion/Induction-and-deduction/Induction-and-deduction.md
      - Induction: Post/Recursion/Induction-and-deduction/Induction.md
      - Structural-induction: Post/Recursion/Induction-and-deduction/Structural-induction.md
      - Coinduction: Post/Recursion/Induction-and-deduction/Coinduction.md
    - Recurrence-relation: Post/Recursion/Recurrence-relation.md
    - Recursion(computer-science): Post/Recursion/Recursion(computer-science).md
    - Recursion-analysis-and-representation: Post/Recursion/Recursion-analysis-and-representation.md
    - Recursion-and-iteration: Post/Recursion/Recursion-and-iteration.md
    - Summary: Post/Recursion/Summary.md
    - Term-with-recursion-in-computer-science: Post/Recursion/Term-with-recursion-in-computer-science.md
  - Turing:
    - Introduction: Post/Turing/index.md
    - Turing-completeness: Post/Turing/Turing-completeness.md
  - Unit: Post/Unit.md
  - Discrete: Post/Discrete.md
  - Context: Post/Context.md
  - Separation-and-independent.md: Post/Separation-and-independent.md
  - Architecture: Post/Architecture.md
  - Time-and-space: Post/Time-and-space.md
  - 0-to-1-and-1-to-many: Post/0-to-1-and-1-to-many.md
  - Closure: Post/Closure.md
  - Glossary: Post/Glossary.md
- About: about.md
plugins:
- search
repo_url: https://github.com/dengking/dengking.github.io
site_author: Kai Deng
site_description: Website of Kai
site_name: Website of Kai
site_url: https://dengking.github.io/
theme:
  name: material
