edit_uri: ''
extra_css:
- css/extra.css
extra_javascript:
- https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML
google_analytics:
- UA-27795084-5
- mkdocs.org
markdown_extensions:
- toc:
    separator: '#'
- admonition
- def_list
- mdx_gh_links:
    repo: mkdocs
    user: mkdocs
- pymdownx.arithmatex
- pymdownx.betterem:
    smart_enable: all
- pymdownx.caret
- pymdownx.critic
- pymdownx.details
- pymdownx.inlinehilite
- pymdownx.magiclink
- pymdownx.mark
- pymdownx.smartsymbols
- pymdownx.superfences
- pymdownx.tasklist:
    custom_checkbox: true
- pymdownx.tilde
nav:
- Home: index.md
- Post:
  - Introduction: Post/index.md
  - Thoughts:
    - Introduction: Post/Thoughts/index.md
  - Law:
    - Introduction: Post/Law/index.md
    - Software-and-hardware:
      - Introduction: Post/Law/Software-and-hardware/index.md
      - Andy-and-Bill's-law: Post/Law/Software-and-hardware/Andy-and-Bill's-law.md
    - Nature:
      - Introduction: Post/Law/Nature/index.md
      - Atomic:
        - Introduction: Post/Law/Nature/Atomic/index.md
      - Transaction:
        - Introduction: Post/Law/Nature/Transaction/index.md
    - Optimization-principle:
      - Introduction: Post/Law/Optimization-principle/index.md
    - Level-in-computer-science:
      - Introduction: Post/Law/Level-in-computer-science/index.md
    - Tradeoff:
      - Introduction: Post/Law/Tradeoff/index.md
    - Opposite:
      - Introduction: Post/Law/Opposite/index.md
      - Lazy-and-eager:
        - Introduction: Post/Law/Opposite/Lazy-and-eager/index.md
    - Time-and-space:
      - Introduction: Post/Law/Time-and-space/index.md
      - Time-and-space-2: Post/Law/Time-and-space/Time-and-space-2.md
    - Meta:
      - Introduction: Post/Law/Meta/index.md
    - Standard-and-implementation:
      - Introduction: Post/Law/Standard-and-implementation/index.md
    - Unit:
      - Introduction: Post/Law/Unit/index.md
  - Abstraction:
    - Abstraction: Post/Abstraction/Abstraction.md
    - Abstraction-and-model: Post/Abstraction/Abstraction-and-model.md
    - Abstract-and-concrete: Post/Abstraction/Abstract-and-concrete.md
    - Abstraction-and-virtual:
      - Introduction: Post/Abstraction/Abstraction-and-virtual/index.md
    - Create-abstraction:
      - Introduction: Post/Abstraction/Create-abstraction/index.md
    - Abstraction-principle:
      - Introduction: Post/Abstraction/Abstraction-principle/index.md
  - Language:
    - Language: Post/Language/Language.md
  - TODO-Turing:
    - Introduction: Post/TODO-Turing/index.md
    - Turing-completeness: Post/TODO-Turing/Turing-completeness.md
  - Glossary: Post/Glossary.md
  - Knowledge-base:
    - Knowledge-base: Post/Knowledge-base/Knowledge-base.md
  - "\u6784\u5EFA\u4E2A\u4EBA\u7F51\u7AD9":
    - Introduction: "Post/\u6784\u5EFA\u4E2A\u4EBA\u7F51\u7AD9/index.md"
- About: about.md
plugins:
- search
repo_url: https://github.com/dengking/dengking.github.io
site_author: DengKing
site_description: Project documentation with Markdown.
site_name: Website of Kai
site_url: https://dengking.github.io/dengking.github.io
theme:
  name: material
