nav:
    - Introduction: index.md
    - Thoughts: Thoughts.md
    - Abstraction: Abstraction
    - Language: Language
    - Formal: Formal
    - Turing: Turing
    - Unit: Unit.md
    - Context: Context.md
    - Separation-and-independent.md: Separation-and-independent.md
    - Time-and-space: Time-and-space.md
    - Standard-and-implementation: Standard-and-implementation.md
    - 0-to-1-and-1-to-many: 0-to-1-and-1-to-many.md
    - Closure: Closure.md
    - Glossary: Glossary.md