nav:
    - Thoughts: Thoughts.md
    - Abstraction: Abstraction.md
    - Model: Model.md
    - Philosophy-level: Philosophy-level.md
    - Philosophy-separation: Philosophy-separation.md
    - Architecture: Architecture.md
    - Time-and-space: Time-and-space.md
    - 0-to-1-and-1-to-many: 0-to-1-and-1-to-many.md