nav:
    - Thoughts: Thoughts.md
    - Abstraction: Abstraction.md
    - Abstraction-and-architecture: Abstraction-and-architecture.md
    - Abstraction-and-model: Abstraction-and-model.md
    - Philosophy-separation: Philosophy-separation.md
    - Architecture: Architecture.md
    - Time-and-space: Time-and-space.md
    - 0-to-1-and-1-to-many: 0-to-1-and-1-to-many.md