nav:
    - Introduction: index.md
    - Thoughts: Thoughts
    - Law: Law
    - Abstraction: Abstraction
    - Language: Language
    - TODO-Turing: TODO-Turing
    - Glossary: Glossary.md
    - Knowledge-base: Knowledge-base
    - 构建个人网站: 构建个人网站
    