nav:
    - Introduction: index.md
    - Thoughts: Thoughts.md
    - Abstraction: Abstraction
    - Language: Language
    - Formal: Formal
    - Recursion: Recursion
    - Iteration: Iteration
    - Turing: Turing
    # 任何recursive defined的，都是离散的，都可以进行计算
    - Discrete: Discrete.md
    - Unit: Unit.md
    - Context: Context.md
    - Separation-and-independent.md: Separation-and-independent.md
    - Architecture: Architecture.md
    - Time-and-space: Time-and-space.md
    - 0-to-1-and-1-to-many: 0-to-1-and-1-to-many.md
    - Closure: Closure.md
    - Glossary: Glossary.md