nav:
    - Introduction: index.md
    - Thoughts: Thoughts.md
    - Abstraction: Abstraction
    - Language: Language
    - Formal: Formal
    - Recursion: Recursion
    - Separation: Separation.md
    - Architecture: Architecture.md
    - Time-and-space: Time-and-space.md
    - 0-to-1-and-1-to-many: 0-to-1-and-1-to-many.md