nav:
    - Introduction: index.md
    - Recursive-Definition: Recursive-Definition.md
    - Recursion: Recursion.md
    - Corecursion: Corecursion.md
    - VS-recursion-VS-corecursion: VS-recursion-VS-corecursion.md
    - Induction-and-deduction: Induction-and-deduction
    - Summary: Summary.md
    - Term-with-recursion-in-computer-science: Term-with-recursion-in-computer-science.md