nav:
    - Abstraction: Abstraction.md
    # 介绍conceptual model
    - Abstraction-and-model: Abstraction-and-model.md
    # 会讨论conceptual model的实现
    - Abstract-and-concrete: Abstract-and-concrete.md
    - Abstraction-and-virtual: Abstraction-and-virtual
    # 当问题越来越复杂，需要考虑的问题越来越多，就需要进行更多的抽象，创造更多的概念，创造更加大的框架
    - Create-abstraction: Create-abstraction
    - Abstraction-principle: Abstraction-principle
