nav:
    - Abstraction: Abstraction.md
    - Abstraction-and-architecture: Abstraction-and-architecture.md
    - Abstraction-and-model: Abstraction-and-model.md
    - Abstraction-and-relation: Abstraction-and-relation.md
    - Abstraction-and-virtual: Abstraction-and-virtual.md