nav:
    - Introduction: index.md
    - Induction-and-deduction: Induction-VS-deduction.md
    - Induction: Induction.md
    - Structural-induction: Structural-induction.md
    - Coinduction: Coinduction.md